// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJWtUJEVCWqW9clQ53g3Wzb5iYTbRflbA',
    appId: '1:403532199541:web:2ceab87e4b42099b54ea3c',
    messagingSenderId: '403532199541',
    projectId: 'taskflow-c5e50',
    authDomain: 'taskflow-c5e50.firebaseapp.com',
    storageBucket: 'taskflow-c5e50.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSDLQJxZCXq32qM-6Bd6CgrZtuJOrYLRM',
    appId: '1:403532199541:android:14beb8259d9cea7154ea3c',
    messagingSenderId: '403532199541',
    projectId: 'taskflow-c5e50',
    storageBucket: 'taskflow-c5e50.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCq0Tyt5jmR9nXTYoHv34GzyXgNpWbO9Lo',
    appId: '1:403532199541:ios:df3e74c62accaacd54ea3c',
    messagingSenderId: '403532199541',
    projectId: 'taskflow-c5e50',
    storageBucket: 'taskflow-c5e50.firebasestorage.app',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCq0Tyt5jmR9nXTYoHv34GzyXgNpWbO9Lo',
    appId: '1:403532199541:ios:df3e74c62accaacd54ea3c',
    messagingSenderId: '403532199541',
    projectId: 'taskflow-c5e50',
    storageBucket: 'taskflow-c5e50.firebasestorage.app',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAJWtUJEVCWqW9clQ53g3Wzb5iYTbRflbA',
    appId: '1:403532199541:web:3c38898661c1562a54ea3c',
    messagingSenderId: '403532199541',
    projectId: 'taskflow-c5e50',
    authDomain: 'taskflow-c5e50.firebaseapp.com',
    storageBucket: 'taskflow-c5e50.firebasestorage.app',
  );
}
